#updated on -
#Wed Apr 08 09:59:17 IST 2026

directory.path.of.fundflow.fundstatus=E\:\\Jobs\\FY2024-25\\FUNDFLOW\\FUND_STATUS\\
directory.path.of.parent.folder.of.financialfolders=E\:\\Jobs\\
directory.path.of.pl.actual=E\:\\Jobs\\FY2023-24\\PL\\ACTUAL\\
directory.path.of.pl.budget=E\:\\Jobs\\FY2023-24\\PL\\BUDGET\\
directory.path.of.pl.expense=E\:\\Jobs\\FY2023-24\\PL\\RESULT_EXPENSE\\
job.status.txt.file.folder=E\:\\Jobs\\JOB_LOGS\\JAVA_JOBS_STATUS_REPORT.txt
debug=true
 
job.batch.id=100
logging.level.root=DEBUG
logs.message=
logs.present=no.logs.areNot.present

 
properties.file.path.outside.jar=E\:/Migrate_And_Execute_Java_Jobs/Executable/config/application.properties
send.email.from=mdshaadansari5@gmail.com
send.email.to=mdshaadansari5@gmail.com
spring.application.name=JAVAJOBS
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.password=@$Welcome!@#123
spring.datasource.url=jdbc\:sqlserver\://SMI-BIDASRP-SRV1;databaseName\=FinanceDashboard;
spring.datasource.username=sa
spring.devtools.restart.enabled=false



# Small pool is enough (batch job, not high concurrency)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# Keep idle connections shorter (not very important for batch)
spring.datasource.hikari.idle-timeout=900000   

# \uD83D\uDD25 IMPORTANT: Must be > your job duration
spring.datasource.hikari.max-lifetime=4700000   

# Keep connection alive during long idle gaps between steps
spring.datasource.hikari.keepalive-time=600000    

# Default is fine
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
